name: notify-teams-channel

on:
  pull_request:
    types: [opened, reopened]
  issues:
    types: [opened, reopened]

jobs:
  notify-teams-channel:
    name: post
    runs-on: ubuntu-latest
    
    steps:
      - name: Notify
        uses: davidwengier/postadaptivecard@ed077f2bd4b80fdaaef21dae2e13a34e556d466d
        if: github.repository == 'dotnet/project-system'
        with:
          webhook_uri: https://microsoft.webhook.office.com/webhookb2/4ba7372f-2799-4677-89f0-7a1aaea3706c@72f988bf-86f1-41af-91ab-2d7cd011db47/IncomingWebhook/461ee56585254d63b67f15afdf6a1513/b4e5dfd6-185f-4aed-90e3-aa15b6f398ba
